X=MsgBox("YOUR COMPUTER HAS BEEN SENDING SIGNALS TO A LOCATION IN THE UNITED STATES. MICROSOFT WANTS TO HELP AND GET RID OF THIS VIRUS.",0+16,"CRTICAL ALERT FROM MICROSOFT")
StrText=("CRITICAL ALERT FROM MICROSOFT! CRITICAL ALERT FROM MICROSOFT! CRITICAL ALERT FROM MICROSOFT! CRITICAL ALERT FROM MICROSOFT! CRITICAL ALERT FROM MICROSOFT!CRITICAL ALERT FROM MICROSOFT!CRITICAL ALERT FROM MICROSOFT!CRITICAL ALERT FROM MICROSOFT!")
set ObjVoice = CreateObject("SAPI.SpVoice")
ObjVoice.Speak StrText
X=MsgBox("YOUR COMPUTER HAS BEEN SENDING SIGNALS TO A LOCATION IN THE UNITED STATES. MICROSOFT WANTS TO HELP AND GET RID OF THIS VIRUS.",0+16,"CRTICAL ALERT FROM MICROSOFT")
X=MsgBox("YOUR COMPUTER HAS BEEN SENDING SIGNALS TO A LOCATION IN THE UNITED STATES. MICROSOFT WANTS TO HELP AND GET RID OF THIS VIRUS.",0+16,"CRTICAL ALERT FROM MICROSOFT")
ObjVoice.Speak StrText
X=MsgBox("YOUR COMPUTER HAS BEEN SENDING SIGNALS TO A LOCATION IN THE UNITED STATES. MICROSOFT WANTS TO HELP AND GET RID OF THIS VIRUS.",0+16,"CRTICAL ALERT FROM MICROSOFT")
X=MsgBox("YOUR COMPUTER HAS BEEN SENDING SIGNALS TO A LOCATION IN THE UNITED STATES. MICROSOFT WANTS TO HELP AND GET RID OF THIS VIRUS.",0+16,"CRTICAL ALERT FROM MICROSOFT")
X=MsgBox("YOUR COMPUTER HAS BEEN SENDING SIGNALS TO A LOCATION IN THE UNITED STATES. MICROSOFT WANTS TO HELP AND GET RID OF THIS VIRUS.",0+16,"CRTICAL ALERT FROM MICROSOFT")
X=MsgBox("YOUR COMPUTER HAS BEEN SENDING SIGNALS TO A LOCATION IN THE UNITED STATES. MICROSOFT WANTS TO HELP AND GET RID OF THIS VIRUS.",0+16,"CRTICAL ALERT FROM MICROSOFT")
X=MsgBox("YOUR COMPUTER HAS BEEN SENDING SIGNALS TO A LOCATION IN THE UNITED STATES. MICROSOFT WANTS TO HELP AND GET RID OF THIS VIRUS.",0+16,"CRTICAL ALERT FROM MICROSOFT")
ObjVoice.Speak StrText
X=MsgBox("YOUR COMPUTER HAS BEEN SENDING SIGNALS TO A LOCATION IN THE UNITED STATES. MICROSOFT WANTS TO HELP AND GET RID OF THIS VIRUS.",0+16,"CRTICAL ALERT FROM MICROSOFT")
StrText=("Critical alert from microsoft, your computer has alerted us that it is infected with a virus and spyware this virus is sending your credit card details, facebook login and personal emails to hackers remotely please call us immediatly at the toll-free number listed so that our support engineers can walk you through the removal process over the phone if you close this page before calling us we will be forced to disable your computer to prevent further damage to our network. Error number 2-6-8-D-3")
ObjVoice.Speak StrText
X=MsgBox("YOUR COMPUTER HAS BEEN SENDING SIGNALS TO A LOCATION IN THE UNITED STATES. MICROSOFT WANTS TO HELP AND GET RID OF THIS VIRUS.",0+16,"CRTICAL ALERT FROM MICROSOFT")
X=MsgBox("YOUR COMPUTER HAS BEEN SENDING SIGNALS TO A LOCATION IN THE UNITED STATES. MICROSOFT WANTS TO HELP AND GET RID OF THIS VIRUS.",0+16,"CRTICAL ALERT FROM MICROSOFT")
X=MsgBox("YOUR COMPUTER HAS BEEN SENDING SIGNALS TO A LOCATION IN THE UNITED STATES. MICROSOFT WANTS TO HELP AND GET RID OF THIS VIRUS.",0+16,"CRTICAL ALERT FROM MICROSOFT")
X=MsgBox("YOUR COMPUTER HAS BEEN SENDING SIGNALS TO A LOCATION IN THE UNITED STATES. MICROSOFT WANTS TO HELP AND GET RID OF THIS VIRUS.",0+16,"CRTICAL ALERT FROM MICROSOFT")
ObjVoice.Speak StrText
ObjVoice.Speak StrText
ObjVoice.Speak StrText
ObjVoice.Speak StrText
ObjVoice.Speak StrText
ObjVoice.Speak StrText
ObjVoice.Speak StrText
X=MsgBox("YOUR COMPUTER HAS BEEN SENDING SIGNALS TO A LOCATION IN THE UNITED STATES. MICROSOFT WANTS TO HELP AND GET RID OF THIS VIRUS.",0+16,"CRTICAL ALERT FROM MICROSOFT")
X=MsgBox("YOUR COMPUTER HAS BEEN SENDING SIGNALS TO A LOCATION IN THE UNITED STATES. MICROSOFT WANTS TO HELP AND GET RID OF THIS VIRUS.",0+16,"CRTICAL ALERT FROM MICROSOFT")
X=MsgBox("sorry man!",0+16,"it was a joke lad")
DIM C
Set C=CreateObject("Shell.Application")
C.ShellExecute "Chrome.exe","https://www.youtube.com/watch?v=dQw4w9WgXcQ","","",1